---
parserOptions:
  ecmaVersion: 2018

extends:
- "eslint:recommended"
- "google"

env:
  es6: true
  node: true
  jest: true

rules:
  max-len: ["error", 120]
  indent: ["error", 4]
  arrow-parens: [2, "as-needed", { "requireForBlockBody": true }]
  no-use-before-define: "error"
  overrides: [
    files: ["src/bin/*"]
  ]

